package com.unbank.robotspider.dao;

import com.unbank.robotspider.entity.ArticleInfoTest;
import com.unbank.robotspider.entity.ArticleInfoTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleInfoTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int countByExample(ArticleInfoTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int deleteByExample(ArticleInfoTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int insert(ArticleInfoTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int insertSelective(ArticleInfoTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    List<ArticleInfoTest> selectByExampleWithBLOBs(ArticleInfoTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    List<ArticleInfoTest> selectByExample(ArticleInfoTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") ArticleInfoTest record, @Param("example") ArticleInfoTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleInfoTest record, @Param("example") ArticleInfoTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByExample(@Param("record") ArticleInfoTest record, @Param("example") ArticleInfoTestExample example);
}