package com.unbank.robotspider.dao;

import com.unbank.robotspider.entity.ArticleContentTest;
import com.unbank.robotspider.entity.ArticleContentTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleContentTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int countByExample(ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int deleteByExample(ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int deleteByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int insert(ArticleContentTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int insertSelective(ArticleContentTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    List<ArticleContentTest> selectByExampleWithBLOBs(ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    List<ArticleContentTest> selectByExample(ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    ArticleContentTest selectByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") ArticleContentTest record, @Param("example") ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") ArticleContentTest record, @Param("example") ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByExample(@Param("record") ArticleContentTest record, @Param("example") ArticleContentTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByPrimaryKeySelective(ArticleContentTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ArticleContentTest record);
}