package com.unbank.robotspider.dao;

import com.unbank.robotspider.entity.CrawlTextTest;
import com.unbank.robotspider.entity.CrawlTextTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlTextTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int countByExample(CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int deleteByExample(CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int deleteByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int insert(CrawlTextTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int insertSelective(CrawlTextTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    List<CrawlTextTest> selectByExampleWithBLOBs(CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    List<CrawlTextTest> selectByExample(CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    CrawlTextTest selectByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") CrawlTextTest record, @Param("example") CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") CrawlTextTest record, @Param("example") CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByExample(@Param("record") CrawlTextTest record, @Param("example") CrawlTextTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByPrimaryKeySelective(CrawlTextTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_text_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CrawlTextTest record);
}