package com.unbank.robotspider.dao;

import com.unbank.robotspider.entity.CrawlTest;
import com.unbank.robotspider.entity.CrawlTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrawlTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int countByExample(CrawlTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int deleteByExample(CrawlTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int deleteByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int insert(CrawlTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int insertSelective(CrawlTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    List<CrawlTest> selectByExample(CrawlTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    CrawlTest selectByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") CrawlTest record, @Param("example") CrawlTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByExample(@Param("record") CrawlTest record, @Param("example") CrawlTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByPrimaryKeySelective(CrawlTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl_test
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    int updateByPrimaryKey(CrawlTest record);
}