package com.unbank.robotspider.entity;

import java.util.Date;

public class ArticleInfoTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.crawl_id
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Integer crawlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.website_id
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Integer websiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.crawl_title
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private String crawlTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.crawl_brief
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private String crawlBrief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.crawl_views
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Integer crawlViews;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.web_name
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private String webName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.url
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.file_index
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Byte fileIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.news_time
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Date newsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.crawl_time
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Date crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.task
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private Byte task;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_test.text
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.crawl_id
     *
     * @return the value of ptf_crawl_test.crawl_id
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Integer getCrawlId() {
        return crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.crawl_id
     *
     * @param crawlId the value for ptf_crawl_test.crawl_id
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.website_id
     *
     * @return the value of ptf_crawl_test.website_id
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.website_id
     *
     * @param websiteId the value for ptf_crawl_test.website_id
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.crawl_title
     *
     * @return the value of ptf_crawl_test.crawl_title
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public String getCrawlTitle() {
        return crawlTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.crawl_title
     *
     * @param crawlTitle the value for ptf_crawl_test.crawl_title
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setCrawlTitle(String crawlTitle) {
        this.crawlTitle = crawlTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.crawl_brief
     *
     * @return the value of ptf_crawl_test.crawl_brief
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public String getCrawlBrief() {
        return crawlBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.crawl_brief
     *
     * @param crawlBrief the value for ptf_crawl_test.crawl_brief
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setCrawlBrief(String crawlBrief) {
        this.crawlBrief = crawlBrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.crawl_views
     *
     * @return the value of ptf_crawl_test.crawl_views
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Integer getCrawlViews() {
        return crawlViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.crawl_views
     *
     * @param crawlViews the value for ptf_crawl_test.crawl_views
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setCrawlViews(Integer crawlViews) {
        this.crawlViews = crawlViews;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.web_name
     *
     * @return the value of ptf_crawl_test.web_name
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public String getWebName() {
        return webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.web_name
     *
     * @param webName the value for ptf_crawl_test.web_name
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setWebName(String webName) {
        this.webName = webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.url
     *
     * @return the value of ptf_crawl_test.url
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.url
     *
     * @param url the value for ptf_crawl_test.url
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.file_index
     *
     * @return the value of ptf_crawl_test.file_index
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Byte getFileIndex() {
        return fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.file_index
     *
     * @param fileIndex the value for ptf_crawl_test.file_index
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setFileIndex(Byte fileIndex) {
        this.fileIndex = fileIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.news_time
     *
     * @return the value of ptf_crawl_test.news_time
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Date getNewsTime() {
        return newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.news_time
     *
     * @param newsTime the value for ptf_crawl_test.news_time
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setNewsTime(Date newsTime) {
        this.newsTime = newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.crawl_time
     *
     * @return the value of ptf_crawl_test.crawl_time
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Date getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.crawl_time
     *
     * @param crawlTime the value for ptf_crawl_test.crawl_time
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setCrawlTime(Date crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.task
     *
     * @return the value of ptf_crawl_test.task
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public Byte getTask() {
        return task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.task
     *
     * @param task the value for ptf_crawl_test.task
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setTask(Byte task) {
        this.task = task;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_test.text
     *
     * @return the value of ptf_crawl_test.text
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_test.text
     *
     * @param text the value for ptf_crawl_test.text
     *
     * @mbggenerated Thu Jan 22 09:11:21 CST 2015
     */
    public void setText(String text) {
        this.text = text;
    }
}