package com.unbank.robotspider.entity;

public class CrawlTextTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_text_test.crawl_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private Integer crawlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_crawl_text_test.text
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_text_test.crawl_id
     *
     * @return the value of ptf_crawl_text_test.crawl_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public Integer getCrawlId() {
        return crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_text_test.crawl_id
     *
     * @param crawlId the value for ptf_crawl_text_test.crawl_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setCrawlId(Integer crawlId) {
        this.crawlId = crawlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_crawl_text_test.text
     *
     * @return the value of ptf_crawl_text_test.text
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_crawl_text_test.text
     *
     * @param text the value for ptf_crawl_text_test.text
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setText(String text) {
        this.text = text;
    }
}