package com.unbank.robotspider.entity;

public class EveryDayNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_day_num.num_id
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    private Integer numId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_day_num.crawl_time
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    private String crawlTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_day_num.num
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_day_num.num_id
     *
     * @return the value of ptf_day_num.num_id
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    public Integer getNumId() {
        return numId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_day_num.num_id
     *
     * @param numId the value for ptf_day_num.num_id
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    public void setNumId(Integer numId) {
        this.numId = numId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_day_num.crawl_time
     *
     * @return the value of ptf_day_num.crawl_time
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    public String getCrawlTime() {
        return crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_day_num.crawl_time
     *
     * @param crawlTime the value for ptf_day_num.crawl_time
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    public void setCrawlTime(String crawlTime) {
        this.crawlTime = crawlTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_day_num.num
     *
     * @return the value of ptf_day_num.num
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_day_num.num
     *
     * @param num the value for ptf_day_num.num
     *
     * @mbggenerated Fri Jul 04 09:31:01 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}