package com.unbank.robotspider.entity;

public class WebsiteParser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.parser_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private Integer parserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.website_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private Integer websiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.list_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String listPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.list_needlesselements_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String listNeedlesselementsPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.contenturl_host
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String contenturlHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.newstitle_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String newstitlePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.newstime_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String newstimePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.newscontent_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String newscontentPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.needlesschars_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String needlesscharsPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.needlesselements_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String needlesselementsPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptf_website_parser.needlesstails_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    private String needlesstailsPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.parser_id
     *
     * @return the value of ptf_website_parser.parser_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public Integer getParserId() {
        return parserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.parser_id
     *
     * @param parserId the value for ptf_website_parser.parser_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setParserId(Integer parserId) {
        this.parserId = parserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.website_id
     *
     * @return the value of ptf_website_parser.website_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.website_id
     *
     * @param websiteId the value for ptf_website_parser.website_id
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.list_path
     *
     * @return the value of ptf_website_parser.list_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getListPath() {
        return listPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.list_path
     *
     * @param listPath the value for ptf_website_parser.list_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setListPath(String listPath) {
        this.listPath = listPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.list_needlesselements_path
     *
     * @return the value of ptf_website_parser.list_needlesselements_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getListNeedlesselementsPath() {
        return listNeedlesselementsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.list_needlesselements_path
     *
     * @param listNeedlesselementsPath the value for ptf_website_parser.list_needlesselements_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setListNeedlesselementsPath(String listNeedlesselementsPath) {
        this.listNeedlesselementsPath = listNeedlesselementsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.contenturl_host
     *
     * @return the value of ptf_website_parser.contenturl_host
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getContenturlHost() {
        return contenturlHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.contenturl_host
     *
     * @param contenturlHost the value for ptf_website_parser.contenturl_host
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setContenturlHost(String contenturlHost) {
        this.contenturlHost = contenturlHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.newstitle_path
     *
     * @return the value of ptf_website_parser.newstitle_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getNewstitlePath() {
        return newstitlePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.newstitle_path
     *
     * @param newstitlePath the value for ptf_website_parser.newstitle_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setNewstitlePath(String newstitlePath) {
        this.newstitlePath = newstitlePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.newstime_path
     *
     * @return the value of ptf_website_parser.newstime_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getNewstimePath() {
        return newstimePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.newstime_path
     *
     * @param newstimePath the value for ptf_website_parser.newstime_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setNewstimePath(String newstimePath) {
        this.newstimePath = newstimePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.newscontent_path
     *
     * @return the value of ptf_website_parser.newscontent_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getNewscontentPath() {
        return newscontentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.newscontent_path
     *
     * @param newscontentPath the value for ptf_website_parser.newscontent_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setNewscontentPath(String newscontentPath) {
        this.newscontentPath = newscontentPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.needlesschars_path
     *
     * @return the value of ptf_website_parser.needlesschars_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getNeedlesscharsPath() {
        return needlesscharsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.needlesschars_path
     *
     * @param needlesscharsPath the value for ptf_website_parser.needlesschars_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setNeedlesscharsPath(String needlesscharsPath) {
        this.needlesscharsPath = needlesscharsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.needlesselements_path
     *
     * @return the value of ptf_website_parser.needlesselements_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getNeedlesselementsPath() {
        return needlesselementsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.needlesselements_path
     *
     * @param needlesselementsPath the value for ptf_website_parser.needlesselements_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setNeedlesselementsPath(String needlesselementsPath) {
        this.needlesselementsPath = needlesselementsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptf_website_parser.needlesstails_path
     *
     * @return the value of ptf_website_parser.needlesstails_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public String getNeedlesstailsPath() {
        return needlesstailsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptf_website_parser.needlesstails_path
     *
     * @param needlesstailsPath the value for ptf_website_parser.needlesstails_path
     *
     * @mbggenerated Tue Jan 20 09:57:02 CST 2015
     */
    public void setNeedlesstailsPath(String needlesstailsPath) {
        this.needlesstailsPath = needlesstailsPath;
    }

	@Override
	public String toString() {
		return "WebsiteParser [parserId=" + parserId + ", websiteId=" + websiteId + ", listPath=" + listPath
				+ ", listNeedlesselementsPath=" + listNeedlesselementsPath + ", contenturlHost=" + contenturlHost
				+ ", newstitlePath=" + newstitlePath + ", newstimePath=" + newstimePath + ", newscontentPath="
				+ newscontentPath + ", needlesscharsPath=" + needlesscharsPath + ", needlesselementsPath="
				+ needlesselementsPath + ", needlesstailsPath=" + needlesstailsPath + "]";
	}
    
    
}